platform :ios, '12.1'

use_frameworks!

install! 'cocoapods', :disable_input_output_paths => true

target 'PaylineSDK_Example' do
  pod 'PaylineSDK', :path => '../'

  target 'PaylineSDK_Tests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
  end
end
